package:
  name: mitarspysigproc
  version: 1.0.0

source:
  git_url: https://github.com/MIT-Adaptive-Radio-Science/sigprocpython
  git_rev: 1.0.0
  # path: ../..

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.20
    - scipy
    - matplotlib

  run:
    - python
    - numpy
    - scipy
    - matplotlib
test:
  imports:
    - mitarspysigproc

about:
  home: https://github.com/MIT-Adaptive-Radio-Science/sigprocpython
  license: None
  summary: Python based signal processing tools
  description: |
    A number of signal processing tools including esitmators, detectors and polyphase filter banks for synthesis and analysis
  dev_url: https://github.com/MIT-Adaptive-Radio-Science/sigprocpython
